name:                activity-graphing
version:             0.1.0.0
github:              "tbidne/activity-graphing"
license:             BSD3
author:              "Thomas Bidne"
maintainer:          "tbidne@gmail.com"
copyright:           "2019 Thomas Bidne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/activity-graphing#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - megaparsec
  - text
  - time

executables:
  activity-graphing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - activity-graphing

tests:
  activity-graphing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - activity-graphing
